export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_REDIRECT_PATH = "AUTH_REDIRECT_PATH";

export const FETCHING_DATA = "FETCHING_DATA";
export const CREATE_EVENT = "CREATE_EVENT";
export const DELETE_EVENT = "DELETE_EVENT";
export const FETCH_ALL_EVENTS = "FETCH_ALL_EVENTS";
export const SET_EVENT_ERROR = "SET_EVENT_ERROR";
export const SET_SUCCESS = "SET_SUCCESS";
export const SET_SELECTED_EVENT = "SET_SELECTED_EVENT";

export const FETCHING_DATA_ATHLETE = "FETCHING_DATA_ATHLETE";
export const CREATE_ATHLETE = "CREATE_ATHLETE";
export const DELETE_ATHLETE = "DELETE_ATHLETE";
export const FETCH_ALL_ATHLETES = "FETCH_ALL_ATHLETES";
export const SET_ATHLETE_ERROR = "SET_ATHLETE_ERROR";
export const SET_SUCCESS_ATHLETE = "SET_SUCCESS_ATHLETE";
export const SET_SELECTED_ATHLETE = "SET_SELECTED_ATHLETE";
